Documentation:
  Enabled: false
<<<<<<< HEAD
LineLength:
  Max: 99
FrozenStringLiteralComment:
  Enabled: false
BlockLength:
  Enabled: false
=======
  LineLength:
  Max: 99
FrozenStringLiteralComment:
  Enabled: false
>>>>>>> ddf52b0... Added the .rubocop.yml that got deleted in a previous commit
