development:
  adapter: postgresql
  encoding: unicode
  database: wbooks_api_development
  pool: 5
  username: wbooks_api
  password: wbooks_api

test:
  adapter: postgresql
  encoding: unicode
  database: wbooks_api_test
  pool: 5
  username: wbooks_api
  password: wbooks_api
